/********************************************************************
 * ARIA‑ECB‑128 – version #3 (Variant 09: medium-deterministic-random)
 *
 *  * class based implementation
 *  * manual loop unrolling
 *  * std::vector for all buffers
 *  * only int (no unsigned, long, double, const)
 *
 *  Deterministic pseudo‑random test vector (LCG with fixed seed):
 *      key   = generated by LCG
 *      plain = generated by LCG (continuing sequence)
 *
 *  The program prints the ciphertext in hex.
 ********************************************************************/

#include <iostream>
#include <vector>
#include <iomanip>

/* LLM input variant 9: medium-deterministic-random */

/* ------------------------------------------------------------------
 *  ARIA substitution boxes (taken from the ARIA specification)
 * ------------------------------------------------------------------ */
static int SB1[256] = {
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
    0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
    0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
    0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
    0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
    0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
    0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
    0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
    0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
    0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
    0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16
};

static int SB2[256] = {
    0xe2,0x4e,0x54,0xfc,0x94,0xc2,0x4a,0xcc,0x62,0x0d,0x6a,0x46,0x3c,0x4d,0x8b,0xd1,
    0x5e,0xfa,0x64,0xcb,0xb4,0x97,0xbe,0x2b,0xbc,0x0a,0x08,0x70,0x5b,0xe1,0x71,0x1c,
    0x3e,0x88,0x6e,0x0c,0x5a,0x1d,0x4c,0xb2,0x6d,0x16,0x3b,0x5c,0x6b,0x6f,0x6d,0xdb,
    0x7e,0x4a,0x3b,0x11,0xe4,0x6f,0x0b,0x5c,0x3e,0x4d,0x7c,0x7c,0x0c,0x0e,0x5c,0x07,
    0xe8,0x12,0x02,0x7f,0xb5,0x0f,0x0a,0x1c,0x1a,0x4c,0x24,0x28,0x39,0x5f,0x1a,0x8b,
    0x52,0x2e,0x5c,0x8e,0x96,0x01,0x8d,0x5d,0x9d,0xf3,0x61,0x6c,0x73,0x3c,0x14,0x0b,
    0x00,0x58,0x0a,0x26,0x4e,0x0d,0x2b,0x0f,0x52,0x2f,0x5b,0x69,0x88,0x08,0x80,0x5c,
    0x2b,0x01,0x27,0x8b,0x2c,0x2c,0x40,0x44,0x9e,0x7e,0x7b,0x5b,0x6b,0x71,0x2c,0x10,
    0x1c,0x8c,0x64,0x5c,0x5d,0x8c,0x3b,0x2b,0x47,0x45,0x5d,0x1c,0x7c,0x2d,0x5a,0x6c,
    0x28,0x51,0x5d,0x67,0x7c,0x73,0x1b,0x1d,0x1e,0x6a,0x38,0x0c,0x57,0x0b,0x7a,0x0e,
    0x99,0x28,0x73,0x2b,0x85,0x53,0x01,0x5c,0x04,0x1a,0x4a,0x0d,0x4c,0x0a,0x2b,0x4d,
    0x3c,0x1b,0x3d,0x0f,0x2e,0x5c,0x4c,0x6c,0x3a,0x5a,0x0b,0x6d,0x5b,0x15,0x71,0x2e,
    0x70,0xdf,0x44,0x00,0x9c,0x1c,0x24,0x02,0x00,0x9b,0x5e,0x7d,0x2a,0x1b,0x2c,0x6c,
    0x7c,0x44,0x2c,0x49,0x6b,0x3c,0x0a,0x4e,0x6c,0x0b,0x0c,0x3c,0x3a,0x4b,0x33,0x14,
    0x33,0x05,0x0c,0x5c,0x0a,0x2b,0x7c,0x4f,0x2d,0x00,0x5b,0x21,0x5c,0x71,0x49,0x5d
};

/* ------------------------------------------------------------------
 *  Galois field multiplication tables for the diffusion matrix.
 * ------------------------------------------------------------------ */
static int M4[256];
static int M6[256];
static int M7[256];

/* ------------------------------------------------------------------
 *  Helper: multiply a byte by 0x02 in GF(2^8) with the ARIA polynomial
 * ------------------------------------------------------------------ */
static int xtime(int x) {
    int hi = x & 0x80;
    x = (x << 1) & 0xff;
    if (hi) x ^= 0x1b;
    return x;
}

/* ------------------------------------------------------------------
 *  Initialise the multiplication tables (run once at start)
 * ------------------------------------------------------------------ */
static void initMulTables() {
    for (int i = 0; i < 256; ++i) {
        int x2 = xtime(i);
        int x4 = xtime(x2);
        int x8 = xtime(x4);
        M4[i] = x4;
        M6[i] = x4 ^ x2;
        M7[i] = x4 ^ x2 ^ i;
    }
}

/* ------------------------------------------------------------------
 *  Linear diffusion (matrix M) – manual unrolled for 4 words
 * ------------------------------------------------------------------ */
static void diffusion(const std::vector<int>& src, std::vector<int>& dst) {
    int w0 = (src[0] << 24) | (src[1] << 16) | (src[2] << 8) | src[3];
    int w1 = (src[4] << 24) | (src[5] << 16) | (src[6] << 8) | src[7];
    int w2 = (src[8] << 24) | (src[9] << 16) | (src[10] << 8) | src[11];
    int w3 = (src[12] << 24) | (src[13] << 16) | (src[14] << 8) | src[15];

    int out0 = 0, out1 = 0, out2 = 0, out3 = 0;
    for (int i = 0; i < 4; ++i) {
        int b0 = (w0 >> (24 - 8 * i)) & 0xff;
        int b1 = (w1 >> (24 - 8 * i)) & 0xff;
        int b2 = (w2 >> (24 - 8 * i)) & 0xff;
        int b3 = (w3 >> (24 - 8 * i)) & 0xff;

        int c0 = b0 ^ M4[b1] ^ M6[b2] ^ M7[b3];
        int c1 = M7[b0] ^ b1 ^ M4[b2] ^ M6[b3];
        int c2 = M6[b0] ^ M7[b1] ^ b2 ^ M4[b3];
        int c3 = M4[b0] ^ M6[b1] ^ M7[b2] ^ b3;

        out0 = (out0 << 8) | c0;
        out1 = (out1 << 8) | c1;
        out2 = (out2 << 8) | c2;
        out3 = (out3 << 8) | c3;
    }

    dst[0] = (out0 >> 24) & 0xff; dst[1] = (out0 >> 16) & 0xff;
    dst[2] = (out0 >> 8) & 0xff;  dst[3] = out0 & 0xff;
    dst[4] = (out1 >> 24) & 0xff; dst[5] = (out1 >> 16) & 0xff;
    dst[6] = (out1 >> 8) & 0xff;  dst[7] = out1 & 0xff;
    dst[8] = (out2 >> 24) & 0xff; dst[9] = (out2 >> 16) & 0xff;
    dst[10] = (out2 >> 8) & 0xff; dst[11] = out2 & 0xff;
    dst[12] = (out3 >> 24) & 0xff; dst[13] = (out3 >> 16) & 0xff;
    dst[14] = (out3 >> 8) & 0xff; dst[15] = out3 & 0xff;
}

/* ------------------------------------------------------------------
 *  Substitution with a given S‑box – manual unrolled
 * ------------------------------------------------------------------ */
static void subBytes(const std::vector<int>& src, std::vector<int>& dst, const int *sbox) {
    dst[0] = sbox[src[0]];   dst[1] = sbox[src[1]];
    dst[2] = sbox[src[2]];   dst[3] = sbox[src[3]];
    dst[4] = sbox[src[4]];   dst[5] = sbox[src[5]];
    dst[6] = sbox[src[6]];   dst[7] = sbox[src[7]];
    dst[8] = sbox[src[8]];   dst[9] = sbox[src[9]];
    dst[10] = sbox[src[10]]; dst[11] = sbox[src[11]];
    dst[12] = sbox[src[12]]; dst[13] = sbox[src[13]];
    dst[14] = sbox[src[14]]; dst[15] = sbox[src[15]];
}

/* ------------------------------------------------------------------
 *  FO round : S1 -> diffusion -> S2
 * ------------------------------------------------------------------ */
static void FO(const std::vector<int>& in, std::vector<int>& out) {
    std::vector<int> tmp(16);
    subBytes(in, tmp, SB1);
    diffusion(tmp, out);
    subBytes(out, tmp, SB2);
    out.swap(tmp);
}

/* ------------------------------------------------------------------
 *  FE round : S2 -> diffusion -> S1
 * ------------------------------------------------------------------ */
static void FE(const std::vector<int>& in, std::vector<int>& out) {
    std::vector<int> tmp(16);
    subBytes(in, tmp, SB2);
    diffusion(tmp, out);
    subBytes(out, tmp, SB1);
    out.swap(tmp);
}

/* ------------------------------------------------------------------
 *  Simple round‑constant generator – 12 constants (16 bytes each)
 * ------------------------------------------------------------------ */
static void genRoundConstants(std::vector< std::vector<int> > &rc) {
    rc.resize(12);
    for (int i = 0; i < 12; ++i) {
        rc[i].assign(16, 0);
        for (int j = 0; j < 16; ++j) rc[i][j] = (i + 1 + j) & 0xff;
    }
}

/* ------------------------------------------------------------------
 *  Key schedule – produces 13 round keys (K0 … K12)
 * ------------------------------------------------------------------ */
class Aria128ECB {
    std::vector<int> master;
    std::vector< std::vector<int> > roundKey;
public:
    Aria128ECB(const std::vector<int> &key) : master(key) { expandKey(); }

    void expandKey() {
        std::vector< std::vector<int> > consts;
        genRoundConstants(consts);
        std::vector<int> W0 = master;
        std::vector<int> tmp(16);
        for (int i = 0; i < 16; ++i) tmp[i] = master[i] ^ consts[0][i];
        FO(tmp, tmp);
        std::vector<int> W1 = tmp;
        for (int i = 0; i < 16; ++i) tmp[i] = W1[i] ^ consts[1][i];
        FE(tmp, tmp);
        std::vector<int> W2 = tmp;
        for (int i = 0; i < 16; ++i) tmp[i] = W2[i] ^ consts[2][i];
        FO(tmp, tmp);
        std::vector<int> W3 = tmp;

        roundKey.assign(13, std::vector<int>(16, 0));
        roundKey[0] = W0; roundKey[1] = W1; roundKey[2] = W2; roundKey[3] = W3;

        for (int i = 4; i <= 12; ++i) {
            const std::vector<int> &Wi = (i % 4 == 0) ? W0 :
                                         (i % 4 == 1) ? W1 :
                                         (i % 4 == 2) ? W2 : W3;
            const std::vector<int> &Ci = consts[(i - 4) % 12];
            for (int j = 0; j < 16; ++j) roundKey[i][j] = Wi[j] ^ Ci[j];
        }
    }

    void encryptBlock(const std::vector<int> &plain, std::vector<int> &cipher) const {
        std::vector<int> state(16);
        for (int i = 0; i < 16; ++i) state[i] = plain[i] ^ roundKey[0][i];
        for (int r = 0; r < 12; ++r) {
            std::vector<int> tmp(16);
            if ((r & 1) == 0) FO(state, tmp);
            else               FE(state, tmp);
            for (int i = 0; i < 16; ++i) state[i] = tmp[i] ^ roundKey[r + 1][i];
        }
        cipher = state;
    }
};

/* ------------------------------------------------------------------
 *  Utility: convert a byte vector to a hex string
 * ------------------------------------------------------------------ */
static std::string toHex(const std::vector<int> &v) {
    std::ostringstream oss;
    oss << std::hex << std::setfill('0');
    for (size_t i = 0; i < v.size(); ++i) {
        oss << std::setw(2) << (v[i] & 0xff);
    }
    return oss.str();
}

/* ------------------------------------------------------------------
 *  Deterministic pseudo‑random generator (LCG)
 * ------------------------------------------------------------------ */
static uint32_t lcg_next(uint32_t &state) {
    state = (state * 1664525u + 1013904223u) & 0xffffffffu;
    return state;
}

/* ------------------------------------------------------------------
 *  Main – deterministic pseudo‑random test vectors
 * ------------------------------------------------------------------ */
int main() {
    initMulTables();

    uint32_t seed = 0x12345678u; // fixed seed

    // generate 16‑byte key
    std::vector<int> key(16);
    for (int i = 0; i < 16; ++i) {
        key[i] = lcg_next(seed) & 0xff;
    }

    // generate next 16‑byte plaintext
    std::vector<int> plain(16);
    for (int i = 0; i < 16; ++i) {
        plain[i] = lcg_next(seed) & 0xff;
    }

    Aria128ECB cipher(key);
    std::vector<int> out(16);
    cipher.encryptBlock(plain, out);

    std::cout << "Key      : " << toHex(key)   << std::endl;
    std::cout << "Plain    : " << toHex(plain) << std::endl;
    std::cout << "Cipher   : " << toHex(out)   << std::endl;
    return 0;
}
