#include <iostream>
#include <vector>

// LLM input variant 9: medium-deterministic-random
// ------------------------------------------------------------------
// Helper: compute the maximal number of regions created by 'numLines'
//          assuming a general position (no parallels, no three concurrent)
// ------------------------------------------------------------------
int calculateRegions(int numLines)
{
    int plusOne = numLines + 1;
    int product = numLines * plusOne;
    int half = product / 2;
    int totalRegions = half + 1;
    return totalRegions;
}

// ------------------------------------------------------------------
// Helper: produce a medium‑sized deterministic pseudo‑random collection
// ------------------------------------------------------------------
std::vector<int> produceTestData()
{
    std::vector<int> data;
    // Deterministic sequence generated by (i * 7 + 3) % 50
    for (int i = 0; i < 15; ++i)
    {
        int val = (i * 7 + 3) % 50; // values in [0,49]
        data.push_back(val);
    }
    return data;
}

// ------------------------------------------------------------------
// Entry point
// ------------------------------------------------------------------
int main()
{
    std::vector<int> lineSamples = produceTestData();
    std::size_t idx = 0;
    while (idx < lineSamples.size())
    {
        int currentLines = lineSamples[idx];
        int computedRegions = calculateRegions(currentLines);
        std::cout << "Lines: " << currentLines
                  << " => Regions: " << computedRegions << '\n';
        ++idx;
    }
    return 0;
}
